// <auto-generated />
using Hierarchy.Infrastructure.Persistence.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hierarchy.Infrastructure.Migrations
{
    [DbContext(typeof(HierarchyDbContext))]
    [Migration("20251228214037_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hierarchy.Infrastructure.Persistence.Entities.HierarchyTableItemEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("HierarchyTableItemsEntity");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Layout"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Navigator",
                            ParentId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            Name = "TopBar",
                            ParentId = 1L
                        },
                        new
                        {
                            Id = 4L,
                            Name = "SiteSettings",
                            ParentId = 1L
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Footer",
                            ParentId = 1L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
